In [2]:
import numpy as np

## Vectors

In [2]:
# a new vector s == array in NumPy
s = np.array([33, 65, 50, 45])
s

array([33, 65, 50, 45])

In [3]:
# the third coordinate
s[2]

50

In [5]:
# the length of a vector
len(s)

4

In [10]:
print("ndim:", s.ndim) # the number of the array's dimensions - n.dim: 1
print("shape:", s.shape) # the shape of the array, all vectors have only length - shape: (4, )

ndim: 1
shape: (4,)


In [11]:
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])

In [12]:
# let's calculate the % of living area in the apartment
share_living_space = apartment[1]/apartment[0]

In [13]:
apartment = np.delete(apartment, [0, 1])
apartment = np.append(apartment, share_living_space)

In [14]:
share_living_space

0.5277310924369748

In [16]:
len(apartment)

5

In [17]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [21]:
# the mean temperature in June
t[5]

28

In [22]:
# the min mean temperature in Rome
t.argmin()

0

In [23]:
# the mean temperature in February 
t[1]

14

In [24]:
# the max mean temperature in Rome
t.argmax()

6

### The vector operations

In [39]:
salary_eur_mother_in_law = np.array([2, 3, 2.5])
salary_rub_husband = np.array([120, 150, 90])
salary_rub_wife = np.array([130, 130, 130])
exch_rate_eur_rub = 72

In [41]:
salary_rub_mother_in_law = salary_eur_mother_in_law * exch_rate_eur_rub
# salary_rub_mother_in_law and salary_eur_mother_in_law are the collinear vectors
salary_rub_mother_in_law

array([144., 216., 180.])

In [42]:
salary_rub_husband + salary_rub_wife + salary_rub_mother_in_law

array([394., 496., 400.])

### Linear Combinations of Vectors

In general, a linear combination is a particular way of combining things (variables, vectors, etc) using scalar multiplication and addition.
(scalar)(vector 1) + (scalar)(vector 2) + (scalar)(vector 3)

**The vector b** can be written as a combination of the three given vectors using scalar multiplication and addition. Specifically,

> b = [3, 6, 9]  
> v1 = [1, 2, 3]  
> v2 = [3, 5, 1]  
> v3 = [8, 0, 0]  

> [3, 6, 9] = 3 * [1, 2, 3] + 0 * [3, 5, 1] + 0 * [8, 0, 0]

Or, using the names given to each vector:

> b = 3 * v1 + 0 * v2 + 0 * v3

Now that we have seen a couple of examples and the general idea, let’s finish with the formal definition of a linear combination of vectors. Let the vectors v1, v2, v3, vn be **vectors** in Rn and c1,c2,..,cn be **scalars**. Then the vector b, where b =c1v1+c2v2+..+cnvn is called **a linear combination of v1,v2,v3,..,vn**. The scalars c1,c2,…,cn are commonly called the **“weights”**.

In [44]:
2*np.array([4,5]) - 3*np.array([2,1]) + 5*np.array([1,0])

array([7, 7])

In [48]:
# Юный предприниматель Вовочка мастерит ракеты на водном топливе и продает их. За 4 недели он смастерил 3, 4, 5 и 9 
# ракет, а продал 1, 5, 3 и 6 ракет соответственно. На изготовление одной ракеты он тратит  рублей, а продаёт их по 
# рублей за штуку. Найдите вектор прибыли Вовочки за эти 4 недели.

-200*np.array([3, 4, 5, 9]) + 400*np.array([1, 5, 3, 6])

array([-200, 1200,  200,  600])

### A scalar product of two vectors

In [3]:
monthly_rent = np.array([65, 70, 120, 30])
makler_fee = np.array([0.4, 0.4, 0.2, 0.8])

In [4]:
np.dot(monthly_rent, makler_fee)

102.0

If a scalar product is equal to 0, it means that the vectors are ortogonal. The angle between them is 90 Degree.

In [7]:
a = np.array([2, 3])
b = np.array([-9, 6])
np.dot(a, b)

0

In [8]:
a = np.array([4, 5, -1])
b = np.array([2, 0, 1])
np.dot(a, b)

7

### Vector length

The length of a vector is the square root of the sum of the squares of the horizontal and vertical components. If the horizontal or vertical component is zero: If a or b is zero, then you don't need the vector length formula. In this case, the length is just the absolute value of the nonzero component.

In [9]:
np.sqrt([4**2 + 6**2 + 1**2])

array([7.28010989])

In [11]:
a = np.array([4, 2, -1])
b = np.array([2, 0, 1])
np.dot(a, b)

7

In [13]:
a = np.array([4, 5, -1])
b = np.array([0, 0, 0])
np.dot(a, b)
# ortogonal

0