In [1]:
import numpy as np

In [2]:
x = np.array([1,2,1,1])
x_c = x - x.mean()
x_st = x_c / np.linalg.norm(x_c)
x_st
y = np.array([70,130,65,60])
y_c = y - y.mean()
y_st = y_c / np.linalg.norm(y_c)
y_st
c = np.array([[1,0.9922],[0.9922,1]])
x_new = (x_st*np.linalg.eig(c)[1][0,0]+y_st*np.linalg.eig(c)[1][1,0])
x_new /= np.linalg.norm(x_new)
np.round(x_new, 4)

array([-0.244 ,  0.8643, -0.2881, -0.3323])

In [3]:
np.linalg.eig(c)

(array([1.9922, 0.0078]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))