In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

In [6]:
a_list = [1, 2, 3]
b_list = [3, 4, 5]
np.array(a_list)*2 + np.array(b_list)

array([ 5,  8, 11])

In [7]:
[2*a+b for a,b in zip(a_list, b_list)]

[5, 8, 11]

In [10]:
sum([a_list, a_list, b_list])

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [9]:
list(map(lambda x: x*2, a_list)) + np.array(b_list)

array([ 5,  8, 11])

In [11]:
a_list + b_list

[1, 2, 3, 3, 4, 5]

In [12]:
np.concatenate([a_list, b_list])

array([1, 2, 3, 3, 4, 5])

In [13]:
np.concatenate(a_list, b_list)

TypeError: 'list' object cannot be interpreted as an integer

In [14]:
np.concatenate((a_list, b_list))

array([1, 2, 3, 3, 4, 5])

In [15]:
list(zip(a_list, b_list))

[(1, 3), (2, 4), (3, 5)]

In [16]:
np.stack([a_list, b_list])

array([[1, 2, 3],
       [3, 4, 5]])